"""adding unique constrain

Revision ID: 3dad0214b7fc
Revises: a780204bbfe4
Create Date: 2026-06-02 02:14:47.637079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dad0214b7fc'
down_revision: Union[str, Sequence[str], None] = 'a780204bbfe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_olympiad', 'applications', ['user_id', 'olympiad_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_olympiad', 'applications', type_='unique')
    # ### end Alembic commands ###
