"""udaping

Revision ID: 7563b8b26188
Revises: dcd3614181f7
Create Date: 2026-06-04 15:25:47.705254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7563b8b26188'
down_revision: Union[str, Sequence[str], None] = 'dcd3614181f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('student_profiles', sa.Column('last_name', sa.String(), nullable=False))
    op.drop_index(op.f('ix_student_profiles_full_name'), table_name='student_profiles')
    op.create_index(op.f('ix_student_profiles_first_name'), 'student_profiles', ['first_name'], unique=False)
    op.create_index(op.f('ix_student_profiles_last_name'), 'student_profiles', ['last_name'], unique=False)
    op.drop_column('student_profiles', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_student_profiles_last_name'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_first_name'), table_name='student_profiles')
    op.create_index(op.f('ix_student_profiles_full_name'), 'student_profiles', ['full_name'], unique=False)
    op.drop_column('student_profiles', 'last_name')
    op.drop_column('student_profiles', 'first_name')
    # ### end Alembic commands ###
