"""studentprofile

Revision ID: dcd3614181f7
Revises: 3dad0214b7fc
Create Date: 2026-06-03 15:47:02.827899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcd3614181f7'
down_revision: Union[str, Sequence[str], None] = '3dad0214b7fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='studentgender'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('college_name', sa.String(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('enrollment_number', sa.String(), nullable=False),
    sa.Column('branch', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_student_profiles_enrollment_number'), 'student_profiles', ['enrollment_number'], unique=True)
    op.create_index(op.f('ix_student_profiles_full_name'), 'student_profiles', ['full_name'], unique=False)
    op.create_index(op.f('ix_student_profiles_phone_number'), 'student_profiles', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_profiles_phone_number'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_full_name'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_enrollment_number'), table_name='student_profiles')
    op.drop_table('student_profiles')
    # ### end Alembic commands ###
